





 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 
  
 using System.Reflection;

 [assembly: AssemblyVersion("0.1.63.0")]
 [assembly: AssemblyFileVersion("0.1.63.0")]

[assembly: KSPAssemblyDependency("ToolbarController", 1, 0)]
[assembly: KSPAssemblyDependency("ClickThroughBlocker", 1, 0)]
